apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pr-image-nodejs-sample
spec:
  type: image
  params:
    - name: url
      value: >-
        image-registry.openshift-image-registry.svc:5000/kubepia/nodejs-sample

